[package]
name = "pea"
version = "0.7.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/peacash"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-address = { version = "0.3.0", path = "../address" }
pea-int = { version = "0.1.0", path = "../int" }
pea-api = { version = "0.3.0", path = "../api" }
pea-block = { version = "0.3.0", path = "../block" }
pea-core = { version = "0.3.0", path = "../core" }
pea-db = { version = "0.4.0", path = "../db" }
pea-logger = { version = "0.1.1", path = "../logger" }
pea-key = { version = "0.2.2", path = "../key" }
pea-stake = { version = "0.3.0", path = "../stake" }
pea-transaction = { version = "0.3.0", path = "../transaction" }
pea-tree = { version = "0.2.1", path = "../tree" }
pea-wallet = { version = "0.4.0", path = "../wallet" }
rocksdb = "0.19.0"
libp2p = { version = "0.45.1", features = ["tcp-tokio"] }
colored = "2.0.0"
bincode = "1.3.3"
log = "0.4.17"
hex = "0.4.3"
tokio = { version = "1.19.2", features = ["full"] }
lazy_static = "1.4.0"
regex = "1.6.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
tempdir = "0.3.7"
clap = { version = "3.2.6", features = ["derive"] }
futures = "0.3.25"
void = "1.0.2"