[package]
name = "pea"
version = "0.5.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

[dependencies]
pea-address = { version = "0.1.1", path = "../address" }
pea-amount = { version = "0.1.1", path = "../amount" }
pea-api = { version = "0.1.1", path = "../api" }
pea-core = { version = "0.1.1", path = "../core" }
pea-db = { version = "0.1.0", path = "../db" }
pea-node = { version = "0.2.2", path = "../node" }
pea-tree = { version = "0.1.1", path = "../tree" }
pea-wallet = { version = "0.2.3", path = "../wallet" }