[package]
name = "pea-pay"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-address = { version = "0.1.1", path = "../address" }
pea-api = { version = "0.1.1", path = "../api" }
pea-amount = { version = "0.1.1", path = "../amount" }
pea-core = { version = "0.1.1", path = "../core" }
pea-key = { version = "0.1.0", path = "../key" }
pea-transaction = { version = "0.1.0", path = "../transaction" }
pea-wallet = { version = "0.2.3", path = "../wallet" }
hex = "0.4.3"
tokio = { version = "1.19.2", features = ["full"] }
clap = { version = "3.2.6", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.6.0"
log = "0.4.17"
colored = "2.0.0"
futures = "0.3.25"