[workspace]
members = [
    "address",
    "api",
    "block",
    "core",
    "db",
    "int",
    "key",
    #"pay",
    "pea",
    "stake",
    "time",
    "transaction",
    "tree",
    "wallet"
]