[package]
name = "pea-wallet"
version = "0.2.3"
edition = "2021"
license = "MIT"
description = "エンドウ"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-core = { version = "0.1.1", path = "../core" }
pea-address = { version = "0.1.1", path = "../address" }
pea-amount = { version = "0.1.1", path = "../amount" }
pea-api = { version = "0.1.1", path = "../api" }
pea-key = { version = "0.1.0", path = "../key" }
pea-stake = { version = "0.1.0", path = "../stake" }
pea-transaction = { version = "0.1.0", path = "../transaction" }
chacha20poly1305 = "0.10.1"
inquire = "0.3.0"
colored = "2.0.0"
argon2 = "0.4.1"
zxcvbn = "2.2.1"
chrono = "0.4.19"
hex = "0.4.3"
crossterm = "0.25.0"
log = "0.4.17"
tokio = { version = "1.19.2", features = ["full"] }
clap = { version = "3.2.6", features = ["derive"] }