[package]
name = "pea-wallet"
version = "0.6.2"
edition = "2021"
license = "MIT"
description = "エンドウ"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-core = { path = "../core" }
pea-address = { path = "../address" }
pea-int = { path = "../int" }
pea-api = { path = "../api" }
pea-key = { path = "../key" }
pea-stake = { path = "../stake" }
pea-transaction = { path = "../transaction" }
chacha20poly1305 = "0.10.1"
inquire = "0.3.0"
colored = "2.0.0"
argon2 = "0.4.1"
zxcvbn = "2.2.1"
chrono = "0.4.23"
hex = "0.4.3"
crossterm = "0.25.0"
log = "0.4.17"
tokio = { version = "1.23.0", features = ["full"] }
clap = { version = "3.2.6", features = ["derive"] }
rand = "0.8.5"