[package]
name = "pea-wallet"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-core = { version = "0.1.0", path = "../core" }
pea-address = { version = "0.1.0", path = "../address" }
pea-amount = { version = "0.1.0", path = "../amount" }
pea-api = { version = "0.1.0", path = "../api" }
chacha20poly1305 = "0.10.1"
inquire = "0.3.0"
colored = "2.0.0"
argon2 = "0.4.1"
zxcvbn = "2.2.1"
chrono = "0.4.19"
termion = "1.5.6"
hex = "0.4.3"