[package]
name = "pea-block"
version = "0.6.1"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-address = { path = "../address" }
pea-core = { path = "../core" }
pea-key = { path = "../key", features = ["vrf"]}
pea-stake = { path = "../stake" }
pea-transaction = { path = "../transaction" }
serde = { version = "1.0.137", features = ["derive"] }
serde-big-array = "0.4.1"
sha2 = "0.10.6"
merkle-cbt = "0.3.2"