[package]
name = "pea-block"
version = "0.6.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-address = { version = "0.6.0", path = "../address" }
pea-core = { version = "0.6.0", path = "../core" }
pea-key = { version = "0.6.0", path = "../key", features = ["vrf"]}
pea-stake = { version = "0.7.0", path = "../stake" }
pea-transaction = { version = "0.8.0", path = "../transaction" }
serde = { version = "1.0.137", features = ["derive"] }
serde-big-array = "0.4.1"
hex = "0.4.3"
bincode = "1.3.3"
sha2 = "0.10.6"
merkle-cbt = "0.3.2"