[package]
name = "pea-block"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-core = { version = "0.2.1", path = "../core" }
pea-key = { version = "0.2.1", path = "../key" }
pea-stake = { version = "0.2.1", path = "../stake" }
pea-transaction = { version = "0.2.1", path = "../transaction" }
serde = { version = "1.0.137", features = ["derive"] }
serde-big-array = "0.4.1"
hex = "0.4.3"
bincode = "1.3.3"