[package]
name = "pea-address"
version = "0.6.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-core = { version = "0.6.0", path = "../core" }
hex = "0.4.3"
sha2 = "0.10.6"