[package]
name = "pea-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
merkle-cbt = "0.3.2"
ed25519-dalek = "1.0.1"