[package]
name = "pea-stake"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-core = { version = "0.1.1", path = "../core" }
ed25519 = "1.5.2"
serde = { version = "1.0.137", features = ["derive"] }
serde-big-array = "0.4.1"
bincode = "1.3.3"