[package]
name = "pea-logger"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"
colored = "2.0.0"
chrono = "0.4.23"