[package]
name = "pea-vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-core = { version = "0.4.0", path = "../core" }
pea-key = { version = "0.3.0", path = "../key" }
rand = "0.7.3"
rand_core = "0.5.1"
sha3 = "0.9.1"
curve25519-dalek = "3.1.1"