[package]
name = "pea-db"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-amount = { version = "0.2.0", path = "../amount" }
pea-block = { version = "0.2.0", path = "../block" }
pea-core = { version = "0.2.0", path = "../core" }
pea-stake = { version = "0.2.0", path = "../stake" }
pea-transaction = { version = "0.2.0", path = "../transaction" }
pea-tree = { version = "0.2.0", path = "../tree" }
rocksdb = "0.19.0"
bincode = "1.3.3"
tempdir = "0.3.7"