[package]
name = "pea-db"
version = "0.7.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-int = { path = "../int" }
pea-block = { path = "../block" }
pea-core = { path = "../core" }
pea-stake = { path = "../stake" }
pea-transaction = { path = "../transaction" }
pea-tree = { path = "../tree" }
rocksdb = "0.19.0"
bincode = "1.3.3"
tempdir = "0.3.7"