[package]
name = "pea-db"
version = "0.3.1"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-int = { version = "0.1.0", path = "../int" }
pea-block = { version = "0.2.1", path = "../block" }
pea-core = { version = "0.2.1", path = "../core" }
pea-stake = { version = "0.2.1", path = "../stake" }
pea-transaction = { version = "0.2.1", path = "../transaction" }
pea-tree = { version = "0.2.1", path = "../tree" }
rocksdb = "0.19.0"
bincode = "1.3.3"
tempdir = "0.3.7"
serde = { version = "1.0.137", features = ["derive"] }
serde-big-array = "0.4.1"