[package]
name = "pea-db"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-amount = { version = "0.1.0", path = "../amount" }
pea-core = { version = "0.1.0", path = "../core" }
pea-tree = { version = "0.1.0", path = "../tree" }
rocksdb = "0.19.0"
bincode = "1.3.3"
tempdir = "0.3.7"