[package]
name = "pea-transaction"
version = "0.8.3"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-address = { path = "../address" }
pea-int = { path = "../int" }
pea-core = { path = "../core" }
pea-key = { path = "../key" }
serde = { version = "1.0.137", features = ["derive"] }
serde-big-array = "0.4.1"
sha2 = "0.10.6"