[package]
name = "pea-pay-db"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-pay-core = { version = "0.1.0", path = "../pay-core" }
rocksdb = "0.19.0"
bincode = "1.3.3"