[package]
name = "pea-tree"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-core = { version = "0.2.0", path = "../core" }
bincode = "1.3.3"
hex = "0.4.3"