[package]
name = "pea-api"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "エンドウ"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/pea"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pea-amount = { version = "0.1.1", path = "../amount" }
pea-core = { version = "0.1.1", path = "../core" }
serde = { version = "1.0.137", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json"] }
hex = "0.4.3"
bincode = "1.3.3"