[package]
name = "pea-api"
version = "0.6.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-stake = { path = "../stake" }
pea-transaction = { path = "../transaction" }
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.23.0", features = ["full"] }
serde_json = "1.0.82"