[package]
name = "pea-api"
version = "0.5.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-stake = { version = "0.7.0", path = "../stake" }
pea-transaction = { version = "0.8.0", path = "../transaction" }
serde = { version = "1.0.137", features = ["derive"] }
hex = "0.4.3"
bincode = "1.3.3"
tokio = { version = "1.23.0", features = ["full"] }
serde_json = "1.0.82"